# Form implementation generated from reading ui file 'projects.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import shutil

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QStringListModel, QSize
from PyQt6.QtWidgets import QAbstractItemView, QWidget
from sqlitedict import SqliteDict

from common.secrets import Secrets
from newReactives import ToolbarBtn, InfoWindow, MyComponentsUi


class Projects_Ui(object):
    def __init__(self):
        self.list_projects = []
        self.selected_project = ""
        self.dialogs = []

    def setupUi(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("""
            QWidget#centralwidget{
            background:#eeedeb;
            }
        """)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.left_side = QtWidgets.QWidget(parent=self.centralwidget)
        self.left_side.setMaximumSize(QtCore.QSize(300, 16777215))
        self.left_side.setObjectName("left_side")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_side)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.left_side)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        self.logo.setMaximumSize(QtCore.QSize(300, 100))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("images/Логотип.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)

        self.addProject = ToolbarBtn(self.left_side, "add_proj")
        self.addProject.setObjectName("addProject")
        self.verticalLayout.addWidget(self.addProject)

        self.listView = CustomListItem(self.left_side)
        self.listView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView.setObjectName("listView")
        self.listView.clicked.connect(lambda x: self.select_project(self.list_projects[x.row()]))
        self.load_list_projects()
        self.verticalLayout.addWidget(self.listView)

        self.horizontalLayout.addWidget(self.left_side)

        self.right_side = QtWidgets.QWidget(parent=self.centralwidget)
        self.right_side.setObjectName("right_side")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_side)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.toolbar = QtWidgets.QWidget(parent=self.right_side)
        self.toolbar.setObjectName("toolbar")
        self.toolbar.setStyleSheet("""
        QWidget#toolbar{
        background:#eeedeb;
        }
        """)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_name_project = QtWidgets.QLabel(parent=self.toolbar)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_name_project.setContentsMargins(10, 0, 10, 3)
        self.label_name_project.setFont(font)
        self.label_name_project.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_name_project)

        self.edit_btn = ProjectToolButton(self.toolbar, "edit")
        self.horizontalLayout_2.addWidget(self.edit_btn)

        self.del_proj_btn = ProjectToolButton(self.toolbar, "del")
        self.del_proj_btn.clicked.connect(self.del_project)
        self.horizontalLayout_2.addWidget(self.del_proj_btn)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.components = ToolbarBtn(self.toolbar, "warehouse")
        self.components.clicked.connect(self.open_my_components)
        self.horizontalLayout_2.addWidget(self.components)
        self.verticalLayout_3.addWidget(self.toolbar)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.right_side)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet("""
         QWidget#scrollAreaWidgetContents{
                   background: white;
                   border: 0px solid black;
                   }
         QScrollArea{
            background: white;
            border: 1px solid #bbb;
            }          
                   """)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 796, 544))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # self.main_grid = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.main_grid = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.main_grid.setContentsMargins(10, 0, 10, 10)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.right_side)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.scrollArea.setWidgetResizable(True)

    def load_list_projects(self):
        self.list_projects = os.listdir('saves/')
        listModel = QStringListModel()
        listModel.setStringList(self.list_projects)
        self.listView.setModel(listModel)

    def select_project(self, name):
        self.selected_project = name
        self.label_name_project.setText(name)
        self.edit_btn.show()
        self.del_proj_btn.show()
        self.load_data_project()

    # Загрузка параметров проекта
    def load_data_project(self):
        self.delete_chield(self.main_grid)

        password = ""
        dec_data_params = []
        dec_data_params_value = []
        with SqliteDict('saves/' + self.selected_project + '/params') as mydict:
            enc_data_params = mydict['params']
            enc_data_params_value = mydict['params_value']
            if self.selected_project not in ['Тарировочные_кривые', 'Примеры']:
                for params, params_value in zip(enc_data_params, enc_data_params_value):
                    dec_data_params.append(Secrets().symmetric_decrypt(params, password).decode())
                    dec_data_params_value.append(Secrets().symmetric_decrypt(params_value, password).decode())
            else:
                dec_data_params = enc_data_params
                dec_data_params_value = enc_data_params_value

        self.goal_name_params_of_project = dec_data_params
        self.goal_value_params_of_project = dec_data_params_value
        self.list_iteration_names = os.listdir('saves/' + self.selected_project + '/')
        self.list_iteration_names.remove('params')
        self.list_iteration_names = self.list_iteration_names or []

        self.list_iter_obj = []

        for name in self.list_iteration_names:
            _iter = Iteration2(self.scrollAreaWidgetContents, self.selected_project, name)
            self.main_grid.addWidget(_iter)
            self.list_iter_obj.append(_iter)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_grid.addItem(spacerItem3)

    def del_project(self):
        name = self.selected_project
        if name != 'Тарировочные_кривые':
            if InfoWindow(f"Вы уверены, что хотите удалить проект:\n{name}?").exec():
                shutil.rmtree('saves\\' + name, ignore_errors=True)
                self.load_list_projects()
                self.label_name_project.setText("")
                self.edit_btn.hide()
                self.del_proj_btn.hide()

    def open_my_components(self):
        if not MyComponentsUi._instance:
            dialog = MyComponentsUi()
            self.dialogs.append(dialog)
            dialog.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ЛКМщик - Мои проекты"))

    def delete_chield(self, loyout):
        while loyout.count():
            child = loyout.takeAt(0)
            if child.widget():
                child.widget().deleteLater()


class CustomListItem(QtWidgets.QListView):
    def __init__(self, parent):
        super(CustomListItem, self).__init__(parent=parent)
        self.setAlternatingRowColors(True)
        self.setMouseTracking(True)
        self.setStyleSheet("""

        QListView {
        	background-color: white;
            border: 0px;
            margin-top: 5px;
            outline: 0;
            font: 600 10pt "Segoe UI Semibold";

        }

        QListView::item {
            border: 0px;
            padding: 6px 10px 6px 10px;

        }

        QListView::item:selected {
            padding: 6px 10px 6px 20px;
        	border:none;
        	color: black;
        	background:qlineargradient(spread:pad, x1:0.989, y1:0.494, x2:0, y2:0.506, stop:0 rgba(0, 0, 0, 0), stop:0.4375 rgba(255, 224, 58, 20), stop:0.755682 rgba(255, 224, 58, 66), stop:1 rgba(255, 224, 58, 255));
        }
        QListView::item:alternate:selected{
            padding: 6px 10px 6px 20px;
        	border:none;
        	color: black;
        	background:qlineargradient(spread:pad, x1:0.989, y1:0.494, x2:0, y2:0.506, stop:0 rgba(0, 0, 0, 0), stop:0.4375 rgba(255, 224, 58, 20), stop:0.755682 rgba(255, 224, 58, 66), stop:1 rgba(255, 224, 58, 255));
        }
        QListView::item:focus{border:none;}

        QListView::item:alternate {
        	background: #eeedeb;

        }

         /* Mouse County floats on the entry */
        QListView::item::hover {
        	background:qlineargradient(spread:pad, x1:0.989, y1:0.494, x2:0, y2:0.506, stop:0 rgba(0, 0, 0, 0), stop:0.4375 rgba(255, 224, 58, 20), stop:0.755682 rgba(255, 224, 58, 66), stop:1 rgba(255, 224, 58, 255));

        }

                """)
        self.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)


class ProjectToolButton(QtWidgets.QPushButton):
    def __init__(self, parent, _type):
        super(ProjectToolButton, self).__init__(parent=parent)
        dict_type = {'edit': ['images/edit.png', 'images/edit-on.png'],
                     "del": ["images/del_project.png", "images/del_project-on.png"],
                     }
        path = dict_type[_type]
        self.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.setMinimumSize(24, 24)
        self.hide()
        self.setContentsMargins(0, 0, 3, 0)
        self.setStyleSheet(
            """
               QPushButton {
            background-image: url""" + f"({path[0]});" + \
            """background-origin: content;
            background-position: left;

            background-repeat: no-repeat;

            border: 0px;

             color: rgb(27, 37, 36);
        }
     QPushButton:hover{
              color: rgb(61, 117, 138);
              background-image:  url""" + f"({path[1]});" + \
            """
            }
            """)


class Iteration:
    START_ROW = 0

    def __init__(self, parent, main_grid: QtWidgets.QGridLayout, project, name):
        Iteration.START_ROW += 4
        self.parent = parent
        self.project = project
        self.name = name
        self.main_grid = main_grid
        self.start = Iteration.START_ROW

        self.iteration_toolbar = QtWidgets.QWidget(self.parent)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.iteration_toolbar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.iter_name = QtWidgets.QLabel(parent=self.iteration_toolbar)
        self.iter_name.setText(name)
        self.horizontalLayout_3.addWidget(self.iter_name)

        self.del_iter_btn = ProjectToolButton(self.iteration_toolbar, "del")
        self.del_iter_btn.show()
        self.horizontalLayout_3.addWidget(self.del_iter_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.main_grid.addWidget(self.iteration_toolbar, self.start, 0, 1, 1000,
                                 alignment=QtCore.Qt.AlignmentFlag.AlignLeft)

        self.list_recepture_names = self.get_list_recepture_names()
        self.list_recepture_obj = []

        for r_name in self.list_recepture_names:
            recepture = Recepture(self.parent, self.main_grid, self.start + 1, r_name, self.iter_data[r_name])

            self.list_recepture_obj.append(recepture)

        Recepture.START_COL = 0

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.main_grid.addItem(spacerItem2)

    def get_list_recepture_names(self):
        with SqliteDict('saves/' + self.project + '/' + self.name) as mydict:
            self.iter_data = dict(mydict)
        sorted_list_key = list(self.iter_data.keys())
        sorted_list_key.sort()
        return sorted_list_key


class Recepture:
    START_COL = 0

    def __init__(self, parent, main_grid: QtWidgets.QGridLayout, start, name, data):
        self.data = data
        self.name = name
        self.parent = parent
        self.main_grid = main_grid
        self.row = start

        self.col = Recepture.START_COL
        Recepture.START_COL += 1

        self.nameArea = QtWidgets.QWidget(parent=self.parent)
        self.nameArea.setMaximumSize(QtCore.QSize(300, 16777215))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.nameArea)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_name = QtWidgets.QLabel(parent=self.nameArea)
        self.label_name.setText(self.name)
        self.horizontalLayout_5.addWidget(self.label_name)

        self.pushButton_7 = QtWidgets.QPushButton(parent=self.nameArea)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.main_grid.addWidget(self.nameArea, self.row, self.col, 1, 1,
                                 alignment=QtCore.Qt.AlignmentFlag.AlignLeft)

        self.consist = QtWidgets.QWidget(parent=self.parent)
        self.consist.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(self.consist)
        self.gridLayout.setObjectName("gridLayout")
        for i, (name, amount) in enumerate(zip(self.data[0], self.data[1])):
            if name.strip() != '':
                lable_n = QtWidgets.QLabel(parent=self.consist)
                lable_n.setText(name)
                self.gridLayout.addWidget(lable_n, i, 0, 1, 1)
                lable_a = QtWidgets.QLabel(parent=self.consist)
                lable_a.setText(amount)
                self.gridLayout.addWidget(lable_a, i, 1, 1, 1)
        self.main_grid.addWidget(self.consist, self.row+1, self.col, 1, 1)

        self.ecsperiment = QtWidgets.QWidget(parent=self.parent)
        self.ecsperiment.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ecsperiment)
        for i, (param, value) in enumerate(zip(self.data[2], self.data[3])):
            if param.strip() != '':
                lable_p = QtWidgets.QLabel(parent=self.ecsperiment)
                lable_p.setText(param)
                self.gridLayout_2.addWidget(lable_p, i, 0, 1, 1)
                lable_v = QtWidgets.QLabel(parent=self.ecsperiment)
                lable_v.setText(value)
                self.gridLayout_2.addWidget(lable_v, i, 1, 1, 1)

        self.main_grid.addWidget(self.ecsperiment, self.row+2, self.col, 1, 1)

        w = self.consist.size().width()
        h = self.consist.size().height()
        self.consist.setStyleSheet("border: 1px solid black;")
        print(w)
        print(h)




class Iteration2(QtWidgets.QWidget):

    def __init__(self, parent, project, name):
        super(Iteration2, self).__init__(parent=parent)
        self.project = project
        self.name = name

        self.vertical_loyout = QtWidgets.QVBoxLayout(self)
        self.iteration_toolbar = QtWidgets.QWidget(self)
        self.iteration_toolbar.setContentsMargins(0,15,0,5 )
        self.iteration_toolbar.setObjectName("iterNameArea")
        self.iteration_toolbar.setStyleSheet("""
        QWidget#iterNameArea{
        border-bottom: 2px solid #ddd;
        }
        """)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.iteration_toolbar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.iter_name = QtWidgets.QLabel(parent=self.iteration_toolbar)
        self.iter_name.setText(name)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.iter_name.setFont(font)
        self.horizontalLayout_3.addWidget(self.iter_name)

        self.del_iter_btn = ProjectToolButton(self.iteration_toolbar, "del")
        self.del_iter_btn.show()
        self.horizontalLayout_3.addWidget(self.del_iter_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.vertical_loyout.addWidget(self.iteration_toolbar)

        self.iter = QtWidgets.QWidget(self)
        self.loyout = QtWidgets.QHBoxLayout(self.iter)
        self.loyout.setSpacing(10)
        self.vertical_loyout.addWidget(self.iter)

        self.list_recepture_names = self.get_list_recepture_names()
        self.list_recepture_obj = []

        list_size = []
        for r_name in self.list_recepture_names:
            recepture = Recepture2(self.iter, r_name, self.iter_data[r_name])
            self.list_recepture_obj.append(recepture)
            self.loyout.addWidget(recepture)
            list_size.append(recepture.get_size())

        max_size = max(list_size)

        for recepture in self.list_recepture_obj:
            while recepture.get_size() < max_size:
                recepture.add_component("", "")

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.loyout.addItem(spacerItem2)



    def get_list_recepture_names(self):
        with SqliteDict('saves/' + self.project + '/' + self.name) as mydict:
            self.iter_data = dict(mydict)
        sorted_list_key = list(self.iter_data.keys())
        sorted_list_key.sort()
        return sorted_list_key


class Recepture2(QtWidgets.QFrame):

    def __init__(self, parent, name, data):
        super(Recepture2, self).__init__(parent=parent)
        self.data = data
        self.name = name
        self.g_loyout = QtWidgets.QVBoxLayout(self)
        self.g_loyout.setContentsMargins(10,10,10,10)
        self.row = 0
        self.row_p = 0
        self.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.setObjectName("recepture")
        self.setStyleSheet("""
        QFrame#recepture{
        border: 2px solid #eeedeb;
        border-radius: 5px;
        background: #fafafa;;
        }
        """)


        self.nameArea = QtWidgets.QWidget(parent=self)
        self.nameArea.setMaximumSize(QtCore.QSize(300, 16777215))
        self.nameArea.setMinimumSize(QtCore.QSize(200, 0))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.nameArea)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0,0,0,0)
        self.label_name = QtWidgets.QLabel(parent=self.nameArea)
        self.label_name.setText(name)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.horizontalLayout_5.addWidget(self.label_name)

        # self.empty = QtWidgets.QLabel(parent=self)
        # self.empty.setText("")

        self.pushButton_7 = QtWidgets.QPushButton(parent=self.nameArea)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setText("...")
        self.pushButton_7.setStyleSheet("""QPushButton{border:0px solid black;}""")
        self.horizontalLayout_5.addWidget(self.pushButton_7, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.g_loyout.addWidget(self.nameArea)
        # self.g_loyout.addWidget()

        self.consist = QtWidgets.QFrame(parent=self)
        self.consist.setMaximumSize(QtCore.QSize(300, 16777215))
        self.vertical_comp_loyout = QtWidgets.QVBoxLayout(self.consist)
        self.vertical_comp_loyout.setObjectName("gridLayout")
        self.vertical_comp_loyout.setContentsMargins(0,0,0,5)
        self.vertical_comp_loyout.setSpacing(1)
        for name, amount in zip(self.data[0], self.data[1]):
            if name.strip() != '':
                self.add_component(name, amount)
        self.g_loyout.addWidget(self.consist)

        self.ecsperiment = QtWidgets.QFrame(parent=self)
        self.ecsperiment.setObjectName("experimentArea")
        self.ecsperiment.setStyleSheet("""
            QFrame#experimentArea{
            border-top: 2px solid #aaa;
            }
        """)
        self.ecsperiment.setMaximumSize(QtCore.QSize(300, 16777215))
        self.vertical_exp_loyout = QtWidgets.QVBoxLayout(self.ecsperiment)
        self.vertical_exp_loyout.setContentsMargins(0,7,0,0)
        self.vertical_exp_loyout.setSpacing(1)
        for param, value in zip(self.data[2], self.data[3]):
            if param.strip() != '':
                self.add_experiment(param, value)

        self.g_loyout.addWidget(self.ecsperiment)

    def add_component(self, name, value):
        if len(name) > 30:
            name = name[0:29] + "..."

        row_w = QtWidgets.QFrame(self.consist)
        if name != "":
            row_w.setObjectName("row_c")
        row_w.setStyleSheet("""
            QFrame#row_c{
            border-bottom: 1px solid #eee;
            border-radius: 2px;
            background: #fafafa;;
            }
        """)
        self.vertical_comp_loyout.addWidget(row_w)
        row_l = QtWidgets.QHBoxLayout(row_w)
        row_l.setContentsMargins(0,0,0,0)
        row_l.setSpacing(5)
        lable_n = QtWidgets.QLabel(parent=row_w)
        lable_n.setText(name)
        row_l.addWidget(lable_n)
        lable_a = QtWidgets.QLabel(parent=row_w)
        lable_a.setText(value)
        row_l.addWidget(lable_a, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.row += 1

    def add_experiment(self, name, value):
        if len(name) > 30:
            name = name[0:29] + "..."

        row_w = QtWidgets.QFrame(self.ecsperiment)
        if name != "":
            row_w.setObjectName("row_c")
        row_w.setStyleSheet("""
                    QFrame#row_c{
                    border-bottom: 1px solid #eee;
                    border-radius: 2px;
                    background: #fafafa;;
                    }
                """)


        self.vertical_exp_loyout.addWidget(row_w)
        row_l = QtWidgets.QHBoxLayout(row_w)
        row_l.setContentsMargins(0,0,0,0)
        row_l.setSpacing(5)
        lable_p = QtWidgets.QLabel(parent=row_w)
        lable_p.setText(name)
        row_l.addWidget(lable_p)
        lable_v = QtWidgets.QLabel(parent=row_w)
        lable_v.setText(value)
        row_l.addWidget(lable_v, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.row_p += 1

    def get_size(self):
        return self.row

    def get_size_experiment(self):
        return self.row_p
